# This file was generated by GoReleaser. DO NOT EDIT.
class Scut < Formula
  desc "Tail for RabbitMQ."
  homepage "https://github.com/kpurdon/scut"
  url "https://github.com/kpurdon/scut/releases/download/v0.2.0/scut_0.2.0_Darwin_x86_64.tar.gz"
  version "0.2.0"
  sha256 "8ed11531fdd688e27191e3a27afb949d9fcb35c35f95e50f4b9139d1fc61206b"

  def install
    bin.install "scut"
  end
end
