# This file was generated by GoReleaser. DO NOT EDIT.
class Scut < Formula
  desc "Tail for RabbitMQ."
  homepage "https://github.com/kpurdon/scut"
  url "https://github.com/kpurdon/scut/releases/download/v0.1.3/scut_0.1.3_Darwin_x86_64.tar.gz"
  version "0.1.3"
  sha256 "b08a240d78d6aad0b3667cb4610c5a13c1f7e48588edb60aad11dcde54fe1d2a"

  def install
    bin.install "scut"
  end
end
